version: 2
jobs:
  build:
    working_directory: /home/ubuntu/dotfiles
    docker:
      - image: jtwp470/dotfiles

    steps:
      - checkout
      - run:
          name: Check python version
          command: python3 -V
      - run:
          name: Clone repos from GitHub
          command: python3 install.py download ${CIRCLE_BRANCH}
      - run:
          name: Deploy my code to your home directory
          command: python3 install.py deploy
      - run:
          name: Initializing
          command: python3 install.py init
      - run:
          name: Tests
          command: python3 install.py test
      - run:
          name: Cleaning
          command: python3 install.py clean
      - run:
          name: Run via cURL command
          command: curl -L https://raw.githubusercontent.com/ryosan-470/dotfiles/${CIRCLE_BRANCH}/install.py | python3
      - run:
          name: Run tests
          command: python3 install.py test
